# Use semantic release to release the branch uisng the config in .releaseerc.json
name: Release using semantic-release
on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'npm'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci --no-fund --no-audit; else npm i --no-fund --no-audit; fi
      
      - name: semantic-release
        run: GITHUB_TOKEN=${{ secrets.GH_TOKEN }} npx semantic-release
